[build]
  base = ""
  publish = "dist/ProEventos-App"
  command = "npm run build"

[context.production.environment]
  NODE_VERSION = "16.15.0"
  NPM_VERSION = "6.14.18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
