[build]
  base = "Front/ProEventos-App"
  publish = "Front/ProEventos-App/dist/ProEventos-App"
  command = "npm run build --prefix Front/ProEventos-App"

[context.production.environment]
  NODE_VERSION = "16.15.0"
  NPM_VERSION = "6.14.18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
